## SDA docker compose file

version: '2'
services:
  sda:
    image: docker.sec.samsung.net:5000/edge/servicedeployment/servicedeploymentagent/ubuntu_x86_64:latest
    hostname: sda
    ports:
      - "48098"
    volumes:
      - /data/db
      - /var/run:/var/run
    networks:
      - integration-network

  sdam:
    image: target-project
    hostname: sdam
    ports:
      - "48099"
    volumes:
      - /data/db
      - /var/run:/var/run
    networks:
      - integration-network

networks:
  integration-network:
    driver: "bridge"


